services:
  - type: web
    name: binance-flask-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
